services: 
    express-app: 
        image: mahdinapec/express-app-uh
        container_name: express-app
        ports: 
            - 8080:8080
            
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes: 
            - //var/run/docker.sock:/var/run/docker.sock
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_POLL_INTERVAL=15
            - DOCKER_API_VERSION=1.40 